/*
    At first, declare all the variables and constants that we need.
    --- randnum is storing the random number being generated by the Math.random() method.
    --- The first three constants are each made to store a reference to the results paragraphs 
        in our HTML, and are used to insert values into the paragraphs later on in the code
    --- The next two constants store references to the form text input and submit button and 
        are used to control submitting the guess later on.
    --- 
*/

let randnum = Math.floor(Math.random()*100)+1;

const guess = document.querySelector('.guesses');
const lastResult = document.querySelector('.lastResult');
const lowOrHi = document.querySelector('.lowOrHi');

const guessSubmit = document.querySelector('.guessSubmit');
const guessField = document.querySelector('.guessField');

let guessCount = 1;
let resetButton;
guessField.focus();

/*
    Main function for making the guess.
    Conditions are used to check the number and display message on the web page accordingly.
    Another function of setgameover() is called to end the game.
*/
function checkGuess(){
    let userGuess = Number(guessField.value);
    if (guessCount===1){
        guess.textContent = 'Previous guesses: ';
    }
    guess.textContent += userGuess + ' ';

    if(userGuess===randnum){
        lastResult.textContent = 'Congratulations! You got it right.';
        lastResult.style.backgroundColor = 'green';
        lowOrHi.textContent='';
        setGameOver();
    }
    else if (guessCount===10){
        lastResult.textContent= 'Game Over!';
        setGameOver();
    }
    else{
        lastResult.textContent = 'Wrong!';
        lastResult.style.backgroundColor='red';
        if (userGuess<randnum){
            lowOrHi.textContent = 'Last guess is low';
        }
        else if (userGuess>randnum){
            lowOrHi.textContent = 'Last guess is high';
        }
    }
    guessCount++;
    guessField.value='';
    guessField.focus();
}

// calling the function for guessing the number on click
guessSubmit.addEventListener('click',checkGuess);


/*
    Ending of the game is implemented.
    Another function of resetgame is called on click event to reset the game for playing again.
*/

function setGameOver(){
    guessField.disabled = true;
    guessSubmit.disabled = true;
    resetButton = document.createElement('button');
    resetButton.textContent = 'Start new game';
    document.body.append(resetButton);
    resetButton.addEventListener('click',resetGame);
}

// Reseting function to bring the game in the original form.
function resetGame(){
    guessCount = 1;
    const resetParas = document.querySelectorAll('.resultParas p');
    for(let i=0; i<resetParas.length; i++){
        resetParas[i].textContent='';
    }
    resetButton.parentNode.removeChild(resetButton);

    guessField.disabled = false;
    guessSubmit.disabled = false;
    guessField.value = '';
    guessField.focus();

    lastResult.style.backgroundColor='white';
    randnum = Math.floor(Math.random()*100)+1;
}

